# site settings

title: deann.dev
description: Online CV
taglong: Dean's CV/Personal Projects
tagshort: CV
url: https://me.deann.dev
baseurl: ""
permalink: pretty
repo: https://github.com/emdeann/reswebsite

# author settings

author:
  name: Dean
  email: me@deann.dev
# NEED PHOTO
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: emdeann
  linkedin: dean-stavropoulos-7a3877284
  stackoverflow: 22895436/dean

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
